version: "3.9"
services:
  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes: [ "mongo_data:/data/db" ]

  api:
    build: .
    ports: ["4000:4000"]
    environment:
      PORT: 4000
      HOST: 0.0.0.0
      MONGO_URI: mongodb://mongo:27017/jobboardpro
      JWT_ACCESS_SECRET: change-me
      JWT_REFRESH_SECRET: change-me
      JWT_ACCESS_EXPIRES: 15m
      JWT_REFRESH_EXPIRES: 7d
    depends_on: [ mongo ]

volumes:
  mongo_data:
